AllCops:
  TargetRubyVersion: 2.4.2
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'
    - 'config/**/*'

Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
