test:
  resource_provider:
    client_options:
      site: http://test.host
      authorize_url: /oauth/authorize
      me_url: /api/v1/me
    client_id: 12345
    client_secret: 12345
  france_connect:
    client_options:
      site: <%= ENV['FRANCE_CONNECT_HOST'] %>
      authorize_url: '/oauth/v1/authorize'
      token_url: '/oauth/v1/token'
      ssl:
        verify: false
    client_id: 12345
    client_secret: 12345

default: &default
  resource_provider:
    client_options:
      site: <%= ENV['OAUTH_HOST'] %>
      authorize_url: /oauth/authorize
      me_url: /api/v1/me
      ssl:
        verify: false # TODO verify it in production env
    client_id: <%= ENV['SIGNUP_OAUTH_CLIENT_ID'] %>
    client_secret: <%= ENV['SIGNUP_OAUTH_CLIENT_SECRET'] %>
  france_connect:
    client_options:
      site: <%= ENV['FRANCE_CONNECT_HOST'] %>
      authorize_url: '/oauth/v1/authorize'
      token_url: '/oauth/v1/token'
      ssl:
        verify: false # TODO verify it in production env
    client_id: <%= ENV['FRANCE_CONNECT_CLIENT_ID'] %>
    client_secret: <%= ENV['FRANCE_CONNECT_CLIENT_SECRET'] %>

development:
  <<: *default

production:
  <<: *default
