---
franceconnect:
  label: FranceConnect
  support_email: support.partenaires@franceconnect.gouv.fr

api_particulier:
  label: API Particulier
  support_email: contact@particulier.api.gouv.fr

api_impot_particulier_sandbox:
  label: API Impôt particulier (Bac à sable)
  support_email: contact@api.gouv.fr

api_impot_particulier_production:
  label: API Impôt particulier (Production)
  support_email: contact@api.gouv.fr

api_impot_particulier_fc_sandbox:
  label: API Impôt particulier (Bac à sable)
  support_email: contact@api.gouv.fr

api_impot_particulier_fc_production:
  label: API Impôt particulier (Production)
  support_email: contact@api.gouv.fr

api_r2p_sandbox:
  label: API R2P (Bac à sable)
  support_email: contact@api.gouv.fr

api_r2p_production:
  label: API R2P (Production)
  support_email: contact@api.gouv.fr

api_ficoba_sandbox:
  label: API FICOBA (Bac à sable)
  support_email: contact@api.gouv.fr

api_ficoba_production:
  label: API FICOBA (Production)
  support_email: contact@api.gouv.fr

api_droits_cnam:
  label: API Droits CNAM
  support_email: contact@api.gouv.fr

api_entreprise:
  label: API Entreprise
  support_email: support@entreprise.api.gouv.fr

preuve_covoiturage:
  label: Registre de preuve de covoiturage
  support_email: contact@covoiturage.beta.gouv.fr

le_taxi_clients:
  label: le.Taxi
  support_email: contact@api.gouv.fr

le_taxi_chauffeurs:
  label: le.Taxi
  support_email: contact@api.gouv.fr

cartobio:
  label: CartoBio
  support_email: cartobio@beta.gouv.fr

aidants_connect:
  label: Aidants Connect
  support_email: contact@aidantsconnect.beta.gouv.fr

francerelance_fc:
  label: FranceRelance - Guichet FranceConnect
  support_email: support.partenaires@franceconnect.gouv.fr

api_service_national:
  label: API Service National
  support_email: contact@api.gouv.fr

api_statut_etudiant:
  label: API Statut étudiant
  support_email: contact@api.gouv.fr

api_hermes_sandbox:
  label: API Hermes (Bac à sable)
  support_email: contact@api.gouv.fr

api_hermes_production:
  label: API Hermes (Production)
  support_email: contact@api.gouv.fr

hubee:
  label: Hubee
  support_email: contact@api.gouv.fr
